# retro-prompts.zsh — flip the CURRENT zsh into a period-correct prompt.
#
#   retro c64      -> READY.        retro amiga   -> 1>
#   retro dos      -> C:\>          retro irix    -> indy 1%
#   retro sun      -> sun%          retro next    -> next%
#   retro plan9    -> term%         retro apple2  -> ]
#   retro bbc      -> >             retro green   -> $
#   retro amber    -> >             retro linux   -> futhark:~$
#   retro          -> list machines
#   retro random   -> pick a random machine: repaint colors + prompt + boot banner
#   retro off      -> restore your normal (starship) prompt AND default colors
#
# `retro <machine>` and `retro random` also repaint the *live* terminal to the
# machine's palette (OSC 4/10/11/12) when retro-palettes.zsh is present — that
# file is generated by `python3 build_profiles.py` from the same spec the iTerm2
# and Ghostty builders use, so the colors never drift. OSC repaint changes
# colors + prompt + banner, but not the font (only a real profile switch does).
#
# Why a command and not per-profile magic: with tmux + starship, a prompt set at
# profile-open is immediately overwritten by starship's precmd hook, and
# ITERM_PROFILE is stale inside tmux. `retro` removes the starship hook while
# active and restores it on `retro off`, so it works in any shell, any profile.
#
# Install (optional): echo 'source ~/Desktop/notebook/code/retro-terminals/retro-prompts.zsh' >> ~/.zshrc
# Or just `source` it in a shell to try it out.

typeset -gA _RETRO_PROMPTS=(
  green    '%F{46}$ %f'
  amber    '%F{214}> %f'
  linux    '%F{250}futhark:%~$ %f'
  sun      '%F{240}sun%% %f'
  irix     '%F{80}indy 1%% %f'
  c64      $'%F{147}READY.\n%f'
  dos      '%F{252}C:\> %f'
  amiga    '%F{255}1> %f'
  next     '%F{245}next%% %f'
  apple2   '%F{46}] %f'
  spectrum '%F{255}> %f'
  atari    '%F{111}READY%f'$'\n'
  bbc      '%F{255}> %f'
  plan9    '%F{240}term%% %f'

  # --- fictional computers ---
  matrix      '%F{46}neo@zion:~$ %f'
  tron        '%F{45}flynn> %f'
  neuromancer '%F{43}case@sprawl:~$ %f'
  hal         '%F{196}HAL> %f'
  pipboy      '%F{40}RobCo> %f'
  severance   '%F{80}MDR> %f'
  cyberpunk   '%F{220}V@nightcity:~$ %f'
  bladerunner '%F{215}esper> %f'
  wopr        '%F{45}WOPR> %f'
  outrun      '%F{205}outrun> %f'
  lcars       '%F{208}LCARS> %f'

  # --- aesthetic movements ---
  steampunk   '%F{179}aether> %f'
  solarpunk   '%F{29}garden> %f'
  dieselpunk  '%F{137}works> %f'
  vaporwave   '%F{159}vapor> %f'
  atompunk    '%F{30}atom> %f'

  # --- Alien / Blade Runner megacorps ---
  openstep    '%F{246}openstep%% %f'
  weyland     '%F{179}wy> %f'
  mother      '%F{43}MU/TH/UR> %f'
  muthur      '%F{46}MU/TH/UR> %f'
  apollo      '%F{75}APOLLO> %f'
  tyrell      '%F{179}tyrell> %f'
  wallace     '%F{80}wallace> %f'
  vk          '%F{208}V-K> %f'
)

typeset -ga _retro_saved_precmd
typeset -g  _retro_active=0

# Directory of THIS file (works when sourced and inside functions), used to find
# retro-palettes.zsh and the retro-banner tool.
typeset -g _RETRO_DIR="${${(%):-%x}:A:h}"

# Live palettes, generated by build_profiles.py. Optional: without it, `retro`
# is prompt-only (its original behavior) and `retro random` is unavailable.
[[ -r "$_RETRO_DIR/retro-palettes.zsh" ]] && source "$_RETRO_DIR/retro-palettes.zsh"

# Repaint the live terminal to a machine's palette via OSC escapes:
#   OSC 4;N  -> ANSI slot N   OSC 10 -> fg   OSC 11 -> bg   OSC 12 -> cursor
# Honored by iTerm2 and Ghostty; modern tmux forwards these to the client
# terminal. Returns 1 (no-op) if the key has no palette loaded.
_retro_apply_palette() {
  local key="$1" e=$'\e' a=$'\a' i
  local bg="${_RETRO_BG[$key]}" fg="${_RETRO_FG[$key]}" cur="${_RETRO_CUR[$key]}"
  [[ -n "$bg" ]] || return 1
  local -a ansi=(${=_RETRO_ANSI[$key]})
  for i in {1..16}; do
    printf '%s]4;%d;#%s%s' "$e" $((i - 1)) "${ansi[i]}" "$a"
  done
  printf '%s]10;#%s%s%s]11;#%s%s%s]12;#%s%s' \
         "$e" "$fg" "$a" "$e" "$bg" "$a" "$e" "$cur" "$a"
}

# Restore the terminal's own configured colors (undo a repaint).
_retro_reset_palette() {
  local e=$'\e' a=$'\a'
  printf '%s]104%s%s]110%s%s]111%s%s]112%s' \
         "$e" "$a" "$e" "$a" "$e" "$a" "$e" "$a"
}

# The full boot experience for one machine: repaint + prompt + banner + gate.
_retro_boot() {
  local key="$1"
  retro "$key"
  [[ -x "$_RETRO_DIR/tools/retro-banner" ]] && \
    "$_RETRO_DIR/tools/retro-banner" "$key" 2>/dev/null
  _retro_spec_line "$key"
  _retro_press_enter
}

# --- Ghostty-native boot -----------------------------------------------------
# When a `ghostty-*` launcher opens a window, the machine's palette, font and
# CRT shader are already loaded natively. The launcher stashes WHICH machine it
# is; here we just wear the period prompt and print the ascii banner — no OSC
# repaint (that would fight the native colors and mis-behave under tmux).
_RETRO_BOOT_STASH="$HOME/.config/ghostty/retro/.boot-machine"

# Set only the prompt for a machine (no palette repaint).
_retro_wear_prompt() {
  local p="${_RETRO_PROMPTS[$1]}"
  [[ -n "$p" ]] || return 0
  if (( ! _retro_active )); then _retro_saved_precmd=("${precmd_functions[@]}"); fi
  precmd_functions=(${precmd_functions:#starship_precmd})
  RPROMPT=''
  PROMPT="$p"
  _retro_active=1
}

# A dim spec line under the banner, gallery-card style:
#   Sci-Fi · HAL 9000  ·  1968
_retro_spec_line() {
  local nm="${_RETRO_NAME[$1]}" era="${_RETRO_ERA[$1]}"
  [[ -n "$nm$era" ]] || return
  [[ -n "$era" ]] && nm="$nm  ·  $era"
  print -P -- "   %F{8}%B$nm%b%f"
}

# "Press ENTER to enter the session" — the boot screen HOLDS until you ack it,
# so the eye-candy no longer flashes past (the whole point). RETRO_BOOT_WAIT=0
# skips the gate and drops you straight to the prompt.
_retro_press_enter() {
  [[ "${RETRO_BOOT_WAIT:-1}" == "1" ]] || return
  [[ -t 0 ]] || return                       # only when stdin is a real terminal
  print -Pn -- "\n   %F{8}▸ press %F{15}%BENTER%b%F{8} to enter ▸%f "
  read -r _retro_ack
  print
}

# The full native boot screen: prompt + banner + spec line + Enter gate.
_retro_boot_native() {
  _retro_wear_prompt "$1"
  [[ -x "$_RETRO_DIR/tools/retro-banner" ]] && \
    "$_RETRO_DIR/tools/retro-banner" "$1" 2>/dev/null
  _retro_spec_line "$1"
  _retro_press_enter
}

# Consume the stash a ghostty-* launcher left (read once, then delete so only
# the first pane of the new window boots).
_retro_consume_boot() {
  [[ -r "$_RETRO_BOOT_STASH" ]] || return 1
  local key; key="$(<"$_RETRO_BOOT_STASH")"
  command rm -f "$_RETRO_BOOT_STASH" 2>/dev/null
  [[ -n "$key" ]] && _retro_boot_native "$key"
}

# Decide the boot behavior from HOW the window was launched:
#   - fresh ghostty-* launch  (stash present)        -> full boot: banner+spec+gate
#   - another window of a native instance ($RETRO_MACHINE set, no stash, e.g. a
#     Cmd-N / Cmd-T window)                          -> quiet: just wear the prompt
#   - iTerm / OSC opt-in (RETRO_RANDOM_ON_START=1)    -> pick a random machine
# $RETRO_MACHINE is set by the machine's Ghostty config (env=), so every window
# in the instance self-identifies without needing the one-shot stash.
_retro_dispatch_start() {
  local machine="${RETRO_MACHINE:-}" fresh=0
  if [[ -r "$_RETRO_BOOT_STASH" ]]; then
    local sk; sk="$(<"$_RETRO_BOOT_STASH")"
    command rm -f "$_RETRO_BOOT_STASH" 2>/dev/null
    fresh=1
    [[ -n "$sk" ]] && machine="$sk"
  fi
  if [[ -n "$machine" ]]; then
    if (( fresh )); then _retro_boot_native "$machine"   # full boot screen
    else _retro_wear_prompt "$machine"; fi               # quiet: prompt only
  elif [[ "${RETRO_RANDOM_ON_START:-0}" == "1" ]]; then
    retro random
  fi
}

retro() {
  emulate -L zsh
  local name="$1"

  if [[ -z "$name" ]]; then
    print -r -- "retro <machine> — one of:"
    print -r -- "  ${(k)_RETRO_PROMPTS}"
    print -r -- "  retro random   (surprise me: colors + prompt + banner)"
    print -r -- "  retro off      (restore your normal prompt and colors)"
    return 0
  fi

  if [[ "$name" == random ]]; then
    if (( ${#_RETRO_ALL} == 0 )); then
      print -r -- "retro: no palettes loaded — run 'python3 build_profiles.py'"
      return 1
    fi
    _retro_boot "${_RETRO_ALL[$((RANDOM % ${#_RETRO_ALL} + 1))]}"
    return
  fi

  if [[ "$name" == off ]]; then
    if (( _retro_active )); then
      precmd_functions=("${_retro_saved_precmd[@]}")   # re-arm starship etc.
      unset PROMPT RPROMPT
      _retro_reset_palette                             # back to profile colors
      _retro_active=0
      print -r -- "retro: off"
    fi
    return 0
  fi

  local p="${_RETRO_PROMPTS[$name]}"
  # A machine is valid if it has a prompt OR a loaded palette (e.g. teletype).
  if [[ -z "$p" && -z "${_RETRO_BG[$name]}" ]]; then
    print -r -- "retro: unknown machine '$name'. try: retro (to list)"
    return 1
  fi

  if (( ! _retro_active )); then
    _retro_saved_precmd=("${precmd_functions[@]}")     # remember the real hooks once
  fi
  precmd_functions=(${precmd_functions:#starship_precmd})  # silence starship redraws
  _retro_apply_palette "$name"                         # repaint (no-op if no palette)
  RPROMPT=''
  PROMPT="${p:-%F{15\}$ %f}"                            # palette-only -> neutral prompt
  _retro_active=1
}

# Open a file in the OS default app (macOS `open`, Linux `xdg-open`).
_retro_open() {
  if command -v open >/dev/null 2>&1; then open "$1"
  elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$1"
  else print -r -- "retro: open it manually -> $1"; fi
}

# retro-studio — the CRT tuner: browse all 39 machines, drag the CRT dials, and
# publish a profile. Opens the committed studio; rebuilds it first if missing.
retro-studio() {
  local f="$_RETRO_DIR/ghostty-studio.html"
  [[ -r "$f" ]] || ( cd "$_RETRO_DIR" && python3 build_ghostty.py --studio >/dev/null 2>&1 )
  _retro_open "$f"
}

# retro-crt — the pure curved-glass CRT playground (no machine browser).
retro-crt() { _retro_open "$_RETRO_DIR/crt-playground.html"; }

# tab-completion: `retro <TAB>` lists the machines
_retro() { compadd random off ${(k)_RETRO_PROMPTS} ${(k)_RETRO_BG}; }
compdef _retro retro 2>/dev/null

# tiny quality-of-life: `retro?` -> help
alias 'retro?'='retro'
