#: cps 22
IMPERIAL PALACE  --  TRANTOR
@sleep 0.4
CLEON XII  ::  DAY 4,711 OF THE GENETIC DYNASTY
@sleep 0.5
STAR BRIDGE          NOMINAL
IMPERIAL LIBRARY     OPEN
OUTER REACH          TWO DELEGATIONS PENDING
@sleep 0.7
PLEASE RESPECT AND ENJOY THE PEACE.
