#: cps 26
PRIME RADIANT  ::  SEALED INSTRUMENT
@sleep 0.4
BEARER   HARI SELDON      STREELING UNIVERSITY
@sleep 0.5
PSYCHOHISTORIC FIELD      RESOLVED
HORIZON                   1,000 YEARS
DIVERGENCE FROM PLAN      0.0031%
@sleep 0.7
VIOLENCE IS THE LAST REFUGE OF THE INCOMPETENT.
@sleep 0.3
                          -- SALVOR HARDIN
